### ISSUE TITLE
Connecting the API to send task updates on RDS discord tracking channel.

### ISSUE THREAD

**Issue by tejaskh3** [Real-Dev-Squad/website-backend#2004]
### Issue Description
In this issue, we need to connect the API which sends task updates on the discord channel.

### Expected Behavior
Task updates should be sent to the dicord.

### Current Behavior

Task updated are stored in DB only.
### Reproducibility

 - [ ] This issue is reproducible
 - [x] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.
