### ISSUE TITLE
Add a new `Other contributions` type

### ISSUE THREAD

**Issue by shubham-y** [Real-Dev-Squad/website-backend#506]
Feature Owner @shubham-y 
Refer [Frontend Issue](https://github.com/Real-Dev-Squad/website-members/issues/313)

## TODO

- [ ] Update the [task object](https://github.com/Real-Dev-Squad/website-members/issues/313) with a new field `isOther`
- [x] Update the [contribution object](https://github.com/Real-Dev-Squad/website-members/issues/313) with new fields `isOther` and `id`  under task object.
- [ ] Change the CREATE and UPDATE tasks endpoints to accept a new type `isOther`
- [ ] Change the GET contributions endpoint to return **task ID**  for all tasks and tasks with **Others type**(similar to Noteworthy tasks)

Handle making a GitHub PR a noteworthy contribution

- Need to first create a task for the PR
- Map taskId to the PR
- Mark isNoteworthy to true for that taskId

**Comment by priyanshk20** [comment]
Assign it to me please.
